apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dumpster-ing
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
        - path: /some-path
          backend:
            serviceName: my-service
            servicePort: 8080